---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}

ticks <- 40

```

```{r}

### AGENTS ###

N <- 20

# Agent ID
A <- seq(1, N)

# Sampling Introvert-Extrovert
I_E <- sample(1:9, N, replace = TRUE, prob =  c(0.05, 0.15, 0.15, 0.1, 0.1, 0.1, 0.15, 0.15, 0.05))/10

# Number of study groups dependent on number of agents (with 4 in each study group)
n_sg <- round(N/4)
studygroup <- rep(1:n_sg, length.out = N)

# Start energy level
energy <- sample(5:9, N, replace = TRUE, prob = NULL)/10

# Sampling individual interest value for each club interest
i_1 <- sample(1:9, N, replace = TRUE, prob = NULL)/10
i_2 <- sample(1:9, N, replace = TRUE, prob = NULL)/10
i_3 <- sample(1:9, N, replace = TRUE, prob = NULL)/10
i_4 <- sample(1:9, N, replace = TRUE, prob = NULL)/10
i_5 <- sample(1:9, N, replace = TRUE, prob = NULL)/10
i_6 <- sample(1:9, N, replace = TRUE, prob = NULL)/10
i_7 <- sample(1:9, N, replace = TRUE, prob = NULL)/10
i_8 <- sample(1:9, N, replace = TRUE, prob = NULL)/10

# How many relations (start: zero)
N_rel <- rep(0, N)

# The specific relations
participate_small <- rep(0, N)
participate_big <- rep(0, N)

```


```{r}

agents <- as.data.frame(cbind(
  A,
  I_E,
  energy,
  N_rel,
  studygroup,
  participate_small,
  participate_big,
  i_1,
  i_2,
  i_3,
  i_4,
  i_5,
  i_6,
  i_7,
  i_8) )

agents$A <- as.factor(A)

agents

```

```{r}
### STUDY GROUP ###

# study group number
s_ID <- seq(1, n_sg)

# How many in each study group
s_size <- as.data.frame(table(agents$studygroup))$Freq

# Meet-up frequency
s_meetup_interval <- sample(3:5, n_sg, replace = TRUE, prob = NULL)


studygroups <- as.data.frame(cbind(
  s_ID,
  s_size,
  s_meetup_interval) )

studygroups

```

```{r}

### CLUBS ###

n_C <- 8

c_ID <- seq(1, n_C)

# Corresponding interest
interest <- c("i_1", "i_2", "i_3", "i_4", "i_5", "i_6", "i_7", "i_8")

# How often they meet up
c_meetup_interval <- round(runif(n_C, 5, 20))

# Changes on how many sign up
n_member <- rep(0, n_C)

# Changes on how many choose to go
n_active <- rep(0, n_C)

clubs <- as.data.frame(cbind(
  c_ID,
  interest,
  n_member,
  n_active,
  c_meetup_interval) )

clubs

```


```{r}

### EVENTS ###

n_E <- 2

event_ID <- seq(1, n_E)

# 1 = < 10 , 2 = 11-50 , 4 = 51-100 , 5 = > 101
e_size <- c("small", "big")

event_meetup_interval <- c(10, 30)

e_small <- seq(4, ticks, by = event_meetup_interval[1])
e_big <- seq(14, ticks, by = event_meetup_interval[2])

events <- as.data.frame(cbind(
  event_ID,
  e_size,
  event_meetup_interval) )

events

```

```{r}

participate <- rep("no", N)

small_event_participation <- as.data.frame(cbind(
  A,
  participate
))

big_event_participation <- as.data.frame(cbind(
  A,
  participate
))

```

```{r}
M <- matrix(data = 0, nrow = N, ncol = N)

# How to increase friendship
#M[1, 6] <- M[1, 6] + 0.3
#M[6, 1] <- M[6, 1] + 0.3

#M[1, 6] <- M[1, 6] + 0.3
#M[6, 1] <- M[6, 1] + 0.3

#if (M[1, 6] > 1) {
#  M[1, 6] <-  1
#  M[6, 1] <-  1
#}

```

```{r}
# Register energy level

energy_level <- as.data.frame(cbind(
  A,
  I_E
  ) )

```

```{r}


for (t in 1:ticks) {

  # EACH DAY FOR EACH AGENT
  
  ### RELATION UPDATE ###
    
  # A small decrease in all "not friends yet"-relations
  for (x in 1:N) {
    for (y in 1:N) {
      if (x-y == 0) {
        M[x, y] <- 0
      } else if (M[x, y] < 1) {
        M[x, y] <- M[x, y] - 0.02
      }
      if (M[x, y] <= 0) {
        M[x, y] <- 0
      }
    }
  } # DONE WITH FRIENDSHIP DECREASE
  
  
  # GOING THROUGH EACH AGENT's DAY
  for (a in 1:N) {
    
    ## SLEEP RECOVERY ##
    # seq = mondays
    if (t %in% seq(1, ticks, by = 5)) {
      agents$energy[a] <- agents$energy[a] + 0.1 # higher on Mondays
    } else {
      agents$energy[a] <- agents$energy[a] + 0.05
    }
    
    if (agents$energy[a] > 1) {
      agents$energy[a] <- 1
    }
    
    
    ## STUDY GROUP ##
    agent_sg <- agents$studygroup[a] # The study group that the agent is in
    
    all_members <- seq(agents$studygroup[a], N, by = n_sg) # Agents that are in the same study group
    
    a_sg_meet <- studygroups$s_meetup_interval[agent_sg] # Extracting meet-up interval
    
    # If date corresponds to study group meeting
    if (t %in% seq(a_sg_meet, ticks, by = a_sg_meet)) {
      
      # Deciding who to socialize with
      who_sg <- all_members[sample(1:length(all_members), 1)]
      
      # Socialize if not agent self or someone that isn't already a friend
      if (a != who_sg & M[a, who_sg] != 1) {
        
        # Socializing
        M[a, who_sg] <- M[a, who_sg] + 0.1
        M[who_sg, a] <- M[who_sg, a] + 0.1
        
        if (M[a, who_sg] >= 1) {
          M[a, who_sg] <- 1
          M[who_sg, a] <- 1
          agents$N_rel[a] <- agents$N_rel[a] + 1
          agents$N_rel[who_sg] <- agents$N_rel[who_sg] + 1
        }
        
        # Energy cost socializing
        cost <- -0.25+agents$I_E[a]/2
        agents$energy[a] <- agents$energy[a] + cost
          
        if (agents$energy[a] < 0 ) {
          agents$energy[a] <- 0
        } else if (agents$energy[a] > 1 ) {
          agents$energy[a] <- 1
        }
        
      }
    } # END OF STUDY GROUP MEETING
    
    
    ##### SOCIAL #####
    
    ### One-to-one Meet-up
    
    # If day corresponds to ""Tuesday" in the week (Day 2 in reach week)
    if (t %in% seq(2, ticks, by = 5)) {
      contact_or_not <- sample(0:1, size = 1, prob = c(1-agents$I_E[a], agents$I_E[a]))
      
      if (contact_or_not == 1) { # If coin = 1, then agent meet someone
        friends <- M[a, ]
        almost_friends <- which(friends > 0 & friends < 1)
        
        if (length(almost_friends) > 0) {
          # Socializing
          who_friend <- almost_friends[sample(1:length(almost_friends), 1)]
          friend_increase <- sample(2:4, size = 1, prob = NULL)/10
          
          M[a, who_friend] <- M[a, who_friend] + friend_increase
          M[who_friend, a] <- M[who_friend, a] + friend_increase
          
          if (M[a, who_friend] >= 1) {
            M[a, who_friend] <- 1
            M[who_friend, a] <- 1
            agents$N_rel[a] <-  agents$N_rel[a] + 1
            agents$N_rel[who_friend] <- agents$N_rel[who_friend] + 1
          } # END N_REL INCREASE
          
        } # END SOCIALIZING
        
        # Energy cost socializing
        cost <- agents$I_E[a]-0.5
        agents$energy[a] <- agents$energy[a] + cost
        
        if (agents$energy[a] > 1) {
          agents$energy[a] <- 1
        } else if (agents$energy[a_mc] < 0) {
          agents$energy[a_mc] <- 0
        }
        
        
        }  # END IF GOING

    }  ### END ONE-TO-ONE MEET-UP ####
    
    
    ### SMALL EVENT: If day corresponds to a small event day
    if (t %in% e_small) {
      e_prob <- (agents$energy[a]-0.5)/2
      go_or_not <- sample(0:1, size = 1, prob = c(0.5-e_prob, 0.3+e_prob))
      
      if(go_or_not == 1) {
        small_event_participation$participate[a] <- "yes"
        agents$participate_small[a] <- agents$participate_small[a] + 1
        
      } else if (go_or_not == 0) {
        small_event_participation$participate[a] <- "no"
      }
      
    } # END OF SMALL EVENT
    
    
  } ### END OF DAY FOR AGENT
  
  
  
  # SMALL EVENT HAPPENING: If day for small event
  if (t %in% e_small) {
    Small_event_happening <- small_event_participation %>%
      filter(participate == "yes")
    
    agents_going <- as.integer(Small_event_happening$A)
    agents_going <- sample(agents_going)
    
    n_dg <- round(length(agents_going)/5)
    
    dg <- rep(1:n_dg, length.out = length(agents_going))
    
    dinnergroups <- as.data.frame(cbind(
      agents_going,
      dg
    ))
    
    for (s in 1:length(agents_going)) {
      
      agent_dg <- dinnergroups$dg[s] # The study group that the agent is in
    
      dg_members <- seq(dinnergroups$dg[s], length(agents_going), by = n_dg) # Agents that are in the same dinnergroup
      
      who_dg <- dg_members[sample(1:length(dg_members), 1)]
      
      # Finding agent number for each dinner group member
      a_mc <- dinnergroups$agents_going[s]
      dg_friend <- dinnergroups$agents_going[who_dg]

      if (a_mc != dg_friend & M[a_mc, dg_friend] != 1) {
        
        # Socializing
        M[a_mc, dg_friend] <- M[a_mc, dg_friend] + 0.3
        M[dg_friend, a_mc] <- M[dg_friend, a_mc] + 0.3
        
        if (M[a_mc, dg_friend] >= 1) {
          M[a_mc, dg_friend] <- 1
          M[dg_friend, a_mc] <- 1
          agents$N_rel[a_mc] <- agents$N_rel[a_mc] + 1
          agents$N_rel[dg_friend] <- agents$N_rel[dg_friend] + 1
        }
        
        # Energy cost socializing
        cost <- (agents$I_E[a_mc]-1)/2
        agents$energy[a_mc] <- agents$energy[a_mc] + cost
        
        if (agents$energy[a_mc] > 1) {
          agents$energy[a_mc] <- 1
        } else if (agents$energy[a_mc] < 0) {
          agents$energy[a_mc] <- 0
        }
        
      }
      
    } # END OF AGENT PARTICIPATING IN SMALL EVENT
    
  } # END OF SMALL EVENT FOR ALL AGENTS
  
  energy_level[t+2] <- agents$energy
  
} # END OF DAY FOR ALL


```


```{r}
energy_level
```

```{r}
# Print how many friends each agent has

n_friends <- rep(0, N)
for (i in 1:N) {
  n_friends[i] <- (length(which(M[i, ] == 1)))
}

n_friends
agents$N_rel


```


